#define IDC_STATIC                              -1

#define IDI_MAIN                                 1

#define IDC_TEXTBOX_FEN                        102
#define IDC_BOARD_CONTROL                      104
#define IDC_RADIOBUTTON_WHITE_TO_MOVE          105
#define IDC_RADIOBUTTON_BLACK_TO_MOVE          106
#define IDC_CHECKBOX_WHITE_CASTLE_KINGSIDE     107
#define IDC_CHECKBOX_WHITE_CASTLE_QUEENSIDE    108
#define IDC_CHECKBOX_BLACK_CASTLE_KINGSIDE     109
#define IDC_CHECKBOX_BLACK_CASTLE_QUEENSIDE    110
#define IDC_TEXTBOX_EN_PASSANT_TARGET_SQUARE   111
#define IDC_TEXTBOX_HALFMOVE_CLOCK             112
#define IDC_TEXTBOX_FULLMOVE_NUMBER            113
#define IDC_STATUSBAR                          114
#define IDM_SQUARE_INFO                        115
#define IDM_CLEAR_SQUARE                       116
#define IDM_ROOK_WHITE                         117
#define IDM_KNIGHT_WHITE                       118
#define IDM_BISHOP_WHITE                       119
#define IDM_QUEEN_WHITE                        120
#define IDM_KING_WHITE                         121
#define IDM_PAWN_WHITE                         122
#define IDM_ROOK_BLACK                         123
#define IDM_KNIGHT_BLACK                       124
#define IDM_BISHOP_BLACK                       125
#define IDM_QUEEN_BLACK                        126
#define IDM_KING_BLACK                         127
#define IDM_PAWN_BLACK                         128
#define IDM_SET_EN_PASSANT_TARGET_SQUARE       129
#define IDM_TOGGLE_CASTLING_RIGHT              130
#define IDM_RESET_TO_STARTING_POSITION         131
#define IDM_EXIT                               132
#define IDM_ABOUT                              133
#define IDC_BUTTON_CLEAR_EN_PASSANT            134
#define IDM_OPEN                               135
#define IDM_SAVE_AS                            136
#define IDM_SAVE                               137
#define IDM_NEW                                138
#define IDM_PLAY_SOUND                         139
#define IDM_VISUALS_NORMAL                     140
#define IDM_VISUALS_GINGER                     141

#define IDS_FEN_ERR_RANK_SEPARATOR_AT_INVALID_POSITION_0      400
#define IDS_FEN_ERR_RANK_OVERFLOW_ADVANCE_0_1                 401
#define IDS_FEN_ERR_BOARD_SEPARATOR_AT_INVALID_POSITION_0     402
#define IDS_FEN_ERR_INVALID_CHARACTER_0_AT_POSITION_1         403
#define IDS_FEN_ERR_RANK_OVERFLOW_CANNOT_PLACE_0_1_AT_2       404
#define IDS_FEN_ERR_EXPECTED_PLAYER_TO_MOVE_0                 405
#define IDS_FEN_ERR_EXPECTED_SPACE_0                          406
#define IDS_FEN_ERR_DUPLICATE_CASTLING_RIGHT_SPECIFIER_0      407
#define IDS_FEN_ERR_CASTLING_RIGHT_SPECIFIER_CONFLICT         408
#define IDS_FEN_ERR_EXPECTED_CASTLING_RIGHTS_SPECIFIER_0      409
#define IDS_FEN_ERR_INVALID_EN_PASSANT_TARGET_SQUARE_FILE_0   410
#define IDS_FEN_ERR_INVALID_EN_PASSANT_TARGET_SQUARE_RANK_0   411
#define IDS_FEN_ERR_INVALID_HALFMOVE_CLOCK_0                  412
#define IDS_FEN_ERR_INVALID_FULLMOVE_NUMBER_0                 413
#define IDS_FEN_ERR_EXPECTED_END_OF_STRING                    414
#define IDS_INVALID_EN_PASSANT_TARGET_SQUARE                  415
#define IDS_INVALID_EN_PASSANT_TARGET_SQUARE_HINT             416
#define IDS_INVALID_FEN_STRING                                417
#define IDS_ROOK                                              418
#define IDS_KNIGHT                                            419
#define IDS_BISHOP                                            420
#define IDS_QUEEN                                             421
#define IDS_KING                                              422
#define IDS_PAWN                                              423
#define IDS_WHITE                                             424
#define IDS_BLACK                                             425
#define IDS_TITLE                                             426
#define IDS_CONFIRM_RESET_CAPTION                             427
#define IDS_CONFIRM_RESET_MESSAGE                             428
#define IDS_ERROR_CAPTION                                     429
#define IDS_FEN_FILES_FILTER                                  430
#define IDS_ALL_FILES_FILTER                                  431
#define IDS_UNSAVED_CHANGES_CAPTION                           432
#define IDS_UNSAVED_CHANGES_MESSAGE                           433
#define IDS_ALLOW_CASTLING_WHITE_KINGSIDE                     434
#define IDS_DISALLOW_CASTLING_WHITE_KINGSIDE                  435
#define IDS_ALLOW_CASTLING_WHITE_QUEENSIDE                    436
#define IDS_DISALLOW_CASTLING_WHITE_QUEENSIDE                 437
#define IDS_ALLOW_CASTLING_BLACK_KINGSIDE                     438
#define IDS_DISALLOW_CASTLING_BLACK_KINGSIDE                  439
#define IDS_ALLOW_CASTLING_BLACK_QUEENSIDE                    440
#define IDS_DISALLOW_CASTLING_BLACK_QUEENSIDE                 441
