package fen_tool

IDI_MAIN                               ::    1

IDC_TEXTBOX_FEN                        ::  102
IDC_BOARD_CONTROL                      ::  104
IDC_RADIOBUTTON_WHITE_TO_MOVE          ::  105
IDC_RADIOBUTTON_BLACK_TO_MOVE          ::  106
IDC_CHECKBOX_WHITE_CASTLE_KINGSIDE     ::  107
IDC_CHECKBOX_WHITE_CASTLE_QUEENSIDE    ::  108
IDC_CHECKBOX_BLACK_CASTLE_KINGSIDE     ::  109
IDC_CHECKBOX_BLACK_CASTLE_QUEENSIDE    ::  110
IDC_TEXTBOX_EN_PASSANT_TARGET_SQUARE   ::  111
IDC_TEXTBOX_HALFMOVE_CLOCK             ::  112
IDC_TEXTBOX_FULLMOVE_NUMBER            ::  113
IDC_STATUSBAR                          ::  114
IDM_SQUARE_INFO                        ::  115
IDM_CLEAR_SQUARE                       ::  116
IDM_ROOK_WHITE                         ::  117
IDM_KNIGHT_WHITE                       ::  118
IDM_BISHOP_WHITE                       ::  119
IDM_QUEEN_WHITE                        ::  120
IDM_KING_WHITE                         ::  121
IDM_PAWN_WHITE                         ::  122
IDM_ROOK_BLACK                         ::  123
IDM_KNIGHT_BLACK                       ::  124
IDM_BISHOP_BLACK                       ::  125
IDM_QUEEN_BLACK                        ::  126
IDM_KING_BLACK                         ::  127
IDM_PAWN_BLACK                         ::  128
IDM_SET_EN_PASSANT_TARGET_SQUARE       ::  129
IDM_TOGGLE_CASTLING_RIGHT              ::  130
IDM_RESET_TO_STARTING_POSITION         ::  131
IDM_EXIT                               ::  132
IDM_ABOUT                              ::  133
IDC_BUTTON_CLEAR_EN_PASSANT            ::  134
IDM_OPEN                               ::  135
IDM_SAVE_AS                            ::  136
IDM_SAVE                               ::  137
IDM_NEW                                ::  138
IDM_PLAY_SOUND                         ::  139
IDM_VISUALS_NORMAL                     ::  140
IDM_VISUALS_GINGER                     ::  141

// String resource IDs
// Convention: The numbers correspond to numbered argument inserts for aprintf `{0}`, `{1}` etc.

IDS_FEN_ERR_RANK_SEPARATOR_AT_INVALID_POSITION_0      :: 400
IDS_FEN_ERR_RANK_OVERFLOW_ADVANCE_0_1                 :: 401
IDS_FEN_ERR_BOARD_SEPARATOR_AT_INVALID_POSITION_0     :: 402
IDS_FEN_ERR_INVALID_CHARACTER_0_AT_POSITION_1         :: 403
IDS_FEN_ERR_RANK_OVERFLOW_CANNOT_PLACE_0_1_AT_2       :: 404
IDS_FEN_ERR_EXPECTED_PLAYER_TO_MOVE_0                 :: 405
IDS_FEN_ERR_EXPECTED_SPACE_0                          :: 406
IDS_FEN_ERR_DUPLICATE_CASTLING_RIGHT_SPECIFIER_0      :: 407
IDS_FEN_ERR_CASTLING_RIGHT_SPECIFIER_CONFLICT         :: 408
IDS_FEN_ERR_EXPECTED_CASTLING_RIGHTS_SPECIFIER_0      :: 409
IDS_FEN_ERR_INVALID_EN_PASSANT_TARGET_SQUARE_FILE_0   :: 410
IDS_FEN_ERR_INVALID_EN_PASSANT_TARGET_SQUARE_RANK_0   :: 411
IDS_FEN_ERR_INVALID_HALFMOVE_CLOCK_0                  :: 412
IDS_FEN_ERR_INVALID_FULLMOVE_NUMBER_0                 :: 413
IDS_FEN_ERR_EXPECTED_END_OF_STRING                    :: 414
IDS_INVALID_EN_PASSANT_TARGET_SQUARE                  :: 415
IDS_INVALID_EN_PASSANT_TARGET_SQUARE_HINT             :: 416
IDS_INVALID_FEN_STRING                                :: 417
IDS_ROOK                                              :: 418
IDS_KNIGHT                                            :: 419
IDS_BISHOP                                            :: 420
IDS_QUEEN                                             :: 421
IDS_KING                                              :: 422
IDS_PAWN                                              :: 423
IDS_WHITE                                             :: 424
IDS_BLACK                                             :: 425
IDS_TITLE                                             :: 426
IDS_CONFIRM_RESET_CAPTION                             :: 427
IDS_CONFIRM_RESET_MESSAGE                             :: 428
IDS_ERROR_CAPTION                                     :: 429
IDS_FEN_FILES_FILTER                                  :: 430
IDS_ALL_FILES_FILTER                                  :: 431
IDS_UNSAVED_CHANGES_CAPTION                           :: 432
IDS_UNSAVED_CHANGES_MESSAGE                           :: 433
IDS_ALLOW_CASTLING_WHITE_KINGSIDE                     :: 434
IDS_DISALLOW_CASTLING_WHITE_KINGSIDE                  :: 435
IDS_ALLOW_CASTLING_WHITE_QUEENSIDE                    :: 436
IDS_DISALLOW_CASTLING_WHITE_QUEENSIDE                 :: 437
IDS_ALLOW_CASTLING_BLACK_KINGSIDE                     :: 438
IDS_DISALLOW_CASTLING_BLACK_KINGSIDE                  :: 439
IDS_ALLOW_CASTLING_BLACK_QUEENSIDE                    :: 440
IDS_DISALLOW_CASTLING_BLACK_QUEENSIDE                 :: 441
